### ISSUE TITLE
test_default can flake

### ISSUE THREAD

**Issue by freddyaboulton** [FeatureLabs/alteryx-open-src-update-checker#44]
Steps to reproduce:
1. Checkout main.
2. pip install -e .
3. pip install -r test-requirements.txt
4.  pytest alteryx_open_src_update_checker/tests/test_ayx_open_source_update_checker.py::test_default

I'm attaching a screen shot of two subsequent runs of `test_default` I shared with @gsheni and @thehomebrewnerd . I found it interesting that even in the second successful test run, the warning about the ft version being out of date still got captured by pytest (You can see that in the "Warnings summary" section). But the test is written in such a way that no warnings should be emitted at all.

![image](https://user-images.githubusercontent.com/41651716/131585033-fced04f8-92f4-47e0-b548-b71f5aa9d63e.png)

**Comment by thehomebrewnerd** [comment]
@freddyaboulton In trying to reproduce this, I found out that the reproducibility of this depends on the setting you have for `ALTERYX_OPEN_SRC_UPDATE_CHECKER` in your environment variables. 

With `ALTERYX_OPEN_SRC_UPDATE_CHECKER=False`, I do not get this behavior, but when it is set to `True` the test flakiness appears.

**Comment by freddyaboulton** [comment]
@thehomebrewnerd That makes a ton of sense! Would explain why my test suite was running the update checker twice.
